# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 510987158b5c45cb54b1e204bb6e02179260b397fbd22622a7da3913408bb5981908c7c95ad00630e716caeb8c8a8d12f28ab9bf6b0e84019fde508abfc79233

test:
  secret_key_base: 7362ccac60039ee66c693c84dd62fe872d4c245919ba2102f2a0093f99469baff96072873052178285305ea7a887c672adb331ab10e32a6db356c519fca2b1c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
